import {
  AppstoreOutline,
  BellOutline,
  BookOutline,
  BulbOutline,
  CheckOutline,
  CloseOutline,
  DashboardOutline,
  DownOutline,
  EllipsisOutline,
  InboxOutline,
  LogoutOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  PlusOutline,
  ProfileOutline,
  QuestionCircleOutline,
  SearchOutline,
  SettingOutline,
  TeamOutline,
  UserOutline,
} from '@ant-design/icons-angular/icons';

export const NZ_ICONS = [
  AppstoreOutline,
  BellOutline,
  BookOutline,
  BulbOutline,
  CheckOutline,
  CloseOutline,
  DashboardOutline,
  DownOutline,
  EllipsisOutline,
  InboxOutline,
  LogoutOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  PlusOutline,
  ProfileOutline,
  QuestionCircleOutline,
  SearchOutline,
  SettingOutline,
  TeamOutline,
  UserOutline,
];
