import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideIcons } from '@ng-icons/core';
import {
  lucideArrowRight,
  lucideBookOpen,
  lucideBot,
  lucideCalendar,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronsUpDown,
  lucideCircleCheck,
  lucideCircleDollarSign,
  lucideCircleX,
  lucideClock,
  lucideEllipsis,
  lucideFolderSearch,
  lucideHouse,
  lucideLifeBuoy,
  lucideLogOut,
  lucideMessageSquare,
  lucideMoon,
  lucidePackage,
  lucidePanelLeft,
  lucidePlay,
  lucideSearch,
  lucideSettings,
  lucideSparkles,
  lucideStore,
  lucideSun,
  lucideTrendingDown,
  lucideTrendingUp,
  lucideUser,
  lucideUserPlus,
  lucideUsers,
  lucideZap,
} from '@ng-icons/lucide';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withComponentInputBinding()),
    provideIcons({
      lucideArrowRight,
      lucideBookOpen,
      lucideBot,
      lucideCalendar,
      lucideChevronLeft,
      lucideChevronRight,
      lucideChevronsUpDown,
      lucideCircleCheck,
      lucideCircleDollarSign,
      lucideCircleX,
      lucideClock,
      lucideEllipsis,
      lucideFolderSearch,
      lucideHouse,
      lucideLifeBuoy,
      lucideLogOut,
      lucideMessageSquare,
      lucideMoon,
      lucidePackage,
      lucidePanelLeft,
      lucidePlay,
      lucideSearch,
      lucideSettings,
      lucideSparkles,
      lucideStore,
      lucideSun,
      lucideTrendingDown,
      lucideTrendingUp,
      lucideUser,
      lucideUserPlus,
      lucideUsers,
      lucideZap,
    }),
  ],
};
