import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZonelessChangeDetection } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideIcons } from '@ng-icons/core';
import {
  lucideArrowRight,
  lucideAtSign,
  lucideBell,
  lucideBold,
  lucideCheck,
  lucideChevronRight,
  lucideChevronsUpDown,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideCircleUserRound,
  lucideCircleX,
  lucideClock,
  lucideCode,
  lucideCommand,
  lucideEllipsis,
  lucideEye,
  lucideFile,
  lucideFilePen,
  lucideFileText,
  lucideFiles,
  lucideFolder,
  lucideFolderGit2,
  lucideFolderOpen,
  lucideGitCommit,
  lucideGitMerge,
  lucideGitPullRequestArrow,
  lucideInbox,
  lucideEyeOff,
  lucideItalic,
  lucideLink2,
  lucideListOrdered,
  lucideListTree,
  lucideLogOut,
  lucideMessageSquare,
  lucideMessageSquarePlus,
  lucideMoon,
  lucideMoreHorizontal,
  lucidePaperclip,
  lucideQuote,
  lucideSearch,
  lucideSettings,
  lucideSmile,
  lucideSmilePlus,
  lucideSun,
  lucideTag,
  lucideUserPlus,
  lucideX,
} from '@ng-icons/lucide';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(routes, withComponentInputBinding()),
    provideIcons({
      lucideArrowRight,
      lucideAtSign,
      lucideBell,
      lucideBold,
      lucideCheck,
      lucideChevronRight,
      lucideChevronsUpDown,
      lucideCircleAlert,
      lucideCircleCheck,
      lucideCircleUserRound,
      lucideCircleX,
      lucideClock,
      lucideCode,
      lucideCommand,
      lucideEllipsis,
      lucideEye,
      lucideFile,
      lucideFilePen,
      lucideFileText,
      lucideFiles,
      lucideFolder,
      lucideFolderGit2,
      lucideFolderOpen,
      lucideGitCommit,
      lucideGitMerge,
      lucideGitPullRequestArrow,
      lucideInbox,
      lucideItalic,
      lucideEyeOff,
      lucideLink2,
      lucideListOrdered,
      lucideListTree,
      lucideLogOut,
      lucideMessageSquare,
      lucideMessageSquarePlus,
      lucideMoon,
      lucideMoreHorizontal,
      lucidePaperclip,
      lucideQuote,
      lucideSearch,
      lucideSettings,
      lucideSmile,
      lucideSmilePlus,
      lucideSun,
      lucideTag,
      lucideUserPlus,
      lucideX,
    }),
  ],
};