import { Author, MarketAgent } from './marketplace.model';

const AUTHORS = {
  acme: { id: 'a-acme', name: 'Acme Studio', handle: '@acme', initials: 'AC', verified: true, bio: 'Building production-grade automations since 2024.', agentCount: 14, totalInstalls: 28400 },
  parallel: { id: 'a-parallel', name: 'Parallel Labs', handle: '@parallel', initials: 'PL', verified: true, bio: 'Open-source agents for engineers.', agentCount: 22, totalInstalls: 41200 },
  nova: { id: 'a-nova', name: 'Nova Tools', handle: '@nova', initials: 'NV', verified: true, bio: 'AI-native productivity tooling.', agentCount: 9, totalInstalls: 15600 },
  loop: { id: 'a-loop', name: 'Loop Systems', handle: '@loop', initials: 'LS', verified: false, bio: 'Workflow automation made simple.', agentCount: 6, totalInstalls: 7200 },
  bolt: { id: 'a-bolt', name: 'Bolt Co.', handle: '@bolt', initials: 'BO', verified: true, bio: 'Lightning-fast integrations.', agentCount: 18, totalInstalls: 32000 },
  mj: { id: 'a-mj', name: 'Mofiro Jean', handle: '@mofirojean', initials: 'MJ', verified: true, bio: 'Open-source contributor. Maker of skills.', agentCount: 4, totalInstalls: 1280 },
} as const satisfies Record<string, Author>;

export const MARKETPLACE_AGENTS: readonly MarketAgent[] = [
  { id: 'mk-001', name: 'Email Inbox Triage Pro', summary: 'Smart inbox routing with multi-team escalation', description: 'Classifies inbound mail with high accuracy, routes to the right team, and escalates urgent threads using configurable rules. Battle-tested at 50+ companies.', icon: 'lucideMail', category: 'productivity', categoryLabel: 'Productivity', author: AUTHORS.acme, tags: ['email', 'classification', 'production'], installs: 12480, rating: 4.8, reviewCount: 312, featured: true, verified: true, isNew: false, isTrending: true, version: '3.2.1', updatedDays: 4, accent: 'from-sky-500/30 to-blue-600/10' },
  { id: 'mk-002', name: 'PDF Field Extractor', summary: 'Pulls structured fields from invoices, contracts, receipts', description: 'OCR + LLM combined to extract line items, totals, dates, and signatures from PDFs. Outputs JSON ready for your warehouse.', icon: 'lucideFileText', category: 'documents', categoryLabel: 'Documents', author: AUTHORS.parallel, tags: ['ocr', 'extraction', 'production'], installs: 8920, rating: 4.6, reviewCount: 214, featured: true, verified: true, isNew: false, isTrending: false, version: '2.4.0', updatedDays: 11, accent: 'from-rose-500/30 to-orange-600/10' },
  { id: 'mk-003', name: 'Lead Score Composer', summary: 'ML-based lead scoring with explainability', description: 'Ranks leads using historical conversion data. Surfaces why each lead scored what it did. Plays nice with HubSpot, Salesforce, and Pipedrive.', icon: 'lucideTarget', category: 'sales', categoryLabel: 'Sales', author: AUTHORS.nova, tags: ['sales', 'ml', 'crm'], installs: 5640, rating: 4.7, reviewCount: 178, featured: true, verified: true, isNew: false, isTrending: true, version: '1.8.3', updatedDays: 2, accent: 'from-emerald-500/30 to-teal-600/10' },
  { id: 'mk-004', name: 'Slack Standup Compiler', summary: 'Generates standup summaries from yesterday\'s activity', description: 'Crawls commits, PRs, and Slack threads to build a per-person standup digest. Posts to your team channel at 9am sharp.', icon: 'lucideMessageSquare', category: 'productivity', categoryLabel: 'Productivity', author: AUTHORS.loop, tags: ['slack', 'standup', 'beta'], installs: 3120, rating: 4.5, reviewCount: 84, featured: true, verified: false, isNew: true, isTrending: false, version: '0.9.1', updatedDays: 1, accent: 'from-violet-500/30 to-purple-600/10' },
  { id: 'mk-005', name: 'Postgres Sync Pro', summary: 'Bidirectional sync between Postgres and your warehouse', description: 'Schema-aware sync with conflict resolution. Supports incremental syncs, partitioning, and dead-letter retry queues.', icon: 'lucideDatabase', category: 'data', categoryLabel: 'Data', author: AUTHORS.parallel, tags: ['postgres', 'warehouse', 'production'], installs: 7240, rating: 4.9, reviewCount: 256, featured: true, verified: true, isNew: false, isTrending: false, version: '4.1.0', updatedDays: 18, accent: 'from-indigo-500/30 to-blue-600/10' },
  { id: 'mk-006', name: 'Stripe Reconciler', summary: 'Match Stripe payouts against accounting entries', description: 'Compares Stripe transactions with your accounting system, flags discrepancies, and auto-files reconciliation reports.', icon: 'lucideCircleDollarSign', category: 'finance', categoryLabel: 'Finance', author: AUTHORS.bolt, tags: ['stripe', 'accounting', 'critical'], installs: 4180, rating: 4.7, reviewCount: 142, featured: false, verified: true, isNew: false, isTrending: false, version: '2.0.4', updatedDays: 25, accent: 'from-amber-500/30 to-orange-600/10' },
  { id: 'mk-007', name: 'GitHub Bug Triager', summary: 'Auto-labels new issues by component + severity', description: 'Reads issue templates, matches against codebase ownership maps, applies labels, and pings the right reviewer.', icon: 'lucideBug', category: 'engineering', categoryLabel: 'Engineering', author: AUTHORS.parallel, tags: ['github', 'triage', 'production'], installs: 6810, rating: 4.6, reviewCount: 187, featured: false, verified: true, isNew: false, isTrending: true, version: '1.4.2', updatedDays: 6, accent: 'from-fuchsia-500/30 to-pink-600/10' },
  { id: 'mk-008', name: 'Calendar Sync Assistant', summary: 'Suggests optimal meeting times across timezones', description: 'Finds the best meeting slot across attendees in different timezones. Avoids deep-work blocks and lunch hours.', icon: 'lucideCalendar', category: 'productivity', categoryLabel: 'Productivity', author: AUTHORS.nova, tags: ['calendar', 'meetings'], installs: 2940, rating: 4.4, reviewCount: 92, featured: false, verified: true, isNew: false, isTrending: false, version: '1.2.0', updatedDays: 14, accent: 'from-cyan-500/30 to-sky-600/10' },
  { id: 'mk-009', name: 'CRM Profile Enricher', summary: 'Auto-fills missing contact fields from external sources', description: 'Looks up LinkedIn, company website, and public sources to fill in missing email, title, and company info.', icon: 'lucideUsers', category: 'sales', categoryLabel: 'Sales', author: AUTHORS.acme, tags: ['crm', 'enrichment'], installs: 5320, rating: 4.5, reviewCount: 158, featured: false, verified: true, isNew: false, isTrending: false, version: '2.8.0', updatedDays: 9, accent: 'from-emerald-500/30 to-green-600/10' },
  { id: 'mk-010', name: 'Doc Summarizer XL', summary: 'Multi-page document condensation with citations', description: 'Reads long documents and produces structured summaries with page references. Supports DOCX, PDF, and Markdown.', icon: 'lucideBookOpen', category: 'documents', categoryLabel: 'Documents', author: AUTHORS.loop, tags: ['summary', 'production'], installs: 4640, rating: 4.6, reviewCount: 134, featured: false, verified: false, isNew: false, isTrending: false, version: '1.6.3', updatedDays: 21, accent: 'from-slate-500/30 to-gray-600/10' },
  { id: 'mk-011', name: 'Webhook Replay', summary: 'Re-play failed webhook events with patch + transform', description: 'Captures failed webhooks, lets you patch the payload, then replays them in the right order. Lifesaver for partner integrations.', icon: 'lucideWebhook', category: 'engineering', categoryLabel: 'Engineering', author: AUTHORS.bolt, tags: ['webhooks', 'replay'], installs: 1880, rating: 4.8, reviewCount: 68, featured: false, verified: true, isNew: true, isTrending: true, version: '0.4.1', updatedDays: 3, accent: 'from-amber-500/30 to-yellow-600/10' },
  { id: 'mk-012', name: 'Contract Risk Flagger', summary: 'LLM-powered review of inbound legal contracts', description: 'Flags risky clauses, missing indemnification, weird payment terms, and surprising auto-renewals. Outputs a redline summary.', icon: 'lucideShield', category: 'documents', categoryLabel: 'Documents', author: AUTHORS.acme, tags: ['legal', 'wip'], installs: 720, rating: 4.3, reviewCount: 22, featured: false, verified: false, isNew: true, isTrending: false, version: '0.2.0', updatedDays: 5, accent: 'from-red-500/30 to-rose-600/10' },
  { id: 'mk-013', name: 'Customer Sentiment Pulse', summary: 'Tracks satisfaction signals across support tickets', description: 'Analyzes ticket tone, response time, and resolution to produce a daily NPS-like sentiment score. Alerts on dips.', icon: 'lucideHeart', category: 'communication', categoryLabel: 'Communication', author: AUTHORS.nova, tags: ['nps', 'support'], installs: 2110, rating: 4.5, reviewCount: 76, featured: false, verified: true, isNew: false, isTrending: false, version: '1.3.1', updatedDays: 12, accent: 'from-pink-500/30 to-rose-600/10' },
  { id: 'mk-014', name: 'Meeting Notes AI', summary: 'Structured notes from Zoom + Google Meet transcripts', description: 'Generates topic-tagged action items, decisions, and follow-ups. Posts to Notion / Linear / Slack automatically.', icon: 'lucidePenTool', category: 'productivity', categoryLabel: 'Productivity', author: AUTHORS.loop, tags: ['meetings', 'notes'], installs: 3460, rating: 4.6, reviewCount: 102, featured: false, verified: false, isNew: false, isTrending: true, version: '2.1.4', updatedDays: 8, accent: 'from-violet-500/30 to-indigo-600/10' },
  { id: 'mk-015', name: 'Mission Control Quickstart', summary: 'Sample agent — get started with Mission Control', description: 'A minimal "hello world" agent showing how to wire prompt, schedule, and output. Great starting point.', icon: 'lucideRocket', category: 'engineering', categoryLabel: 'Engineering', author: AUTHORS.mj, tags: ['beginner', 'tutorial'], installs: 480, rating: 4.9, reviewCount: 38, featured: false, verified: true, isNew: true, isTrending: false, version: '1.0.0', updatedDays: 0, accent: 'from-primary/30 to-emerald-600/10' },
];

export const CATEGORIES: readonly { value: 'all' | MarketAgent['category']; label: string; icon: string }[] = [
  { value: 'all', label: 'All', icon: 'lucideStore' },
  { value: 'productivity', label: 'Productivity', icon: 'lucideZap' },
  { value: 'sales', label: 'Sales', icon: 'lucideTarget' },
  { value: 'documents', label: 'Documents', icon: 'lucideFileText' },
  { value: 'data', label: 'Data', icon: 'lucideDatabase' },
  { value: 'engineering', label: 'Engineering', icon: 'lucideBug' },
  { value: 'finance', label: 'Finance', icon: 'lucideCircleDollarSign' },
  { value: 'communication', label: 'Communication', icon: 'lucideMessageSquare' },
];