import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideIcons } from '@ng-icons/core';
import { provideMarkdown } from 'ngx-markdown';
import {
  lucideArchive,
  lucideArrowRight,
  lucideArrowUp,
  lucideBookOpen,
  lucideCheck,
  lucideChevronDown,
  lucideChevronRight,
  lucideCircleAlert,
  lucideCircleHelp,
  lucideCircleUser,
  lucideCopy,
  lucideEllipsis,
  lucideEllipsisVertical,
  lucideFolder,
  lucideFolderOpen,
  lucideHouse,
  lucideLogOut,
  lucideMessageCircle,
  lucideMoon,
  lucidePanelLeft,
  lucidePaperclip,
  lucidePencil,
  lucidePin,
  lucidePinOff,
  lucidePlus,
  lucideRefreshCw,
  lucideSearch,
  lucideSend,
  lucideSettings,
  lucideShare2,
  lucideSparkles,
  lucideStar,
  lucideSun,
  lucideThumbsDown,
  lucideThumbsUp,
  lucideTrash2,
  lucideUser,
  lucideX,
} from '@ng-icons/lucide';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideHttpClient(),
    provideMarkdown(),
    provideRouter(routes, withComponentInputBinding()),
    provideIcons({
      lucideArchive,
      lucideArrowRight,
      lucideArrowUp,
      lucideBookOpen,
      lucideCheck,
      lucideChevronDown,
      lucideChevronRight,
      lucideCircleAlert,
      lucideCircleHelp,
      lucideCircleUser,
      lucideCopy,
      lucideEllipsis,
      lucideEllipsisVertical,
      lucideFolder,
      lucideFolderOpen,
      lucideHouse,
      lucideLogOut,
      lucideMessageCircle,
      lucideMoon,
      lucidePanelLeft,
      lucidePaperclip,
      lucidePencil,
      lucidePin,
      lucidePinOff,
      lucidePlus,
      lucideRefreshCw,
      lucideSearch,
      lucideSend,
      lucideSettings,
      lucideShare2,
      lucideSparkles,
      lucideStar,
      lucideSun,
      lucideThumbsDown,
      lucideThumbsUp,
      lucideTrash2,
      lucideUser,
      lucideX,
    }),
  ],
};
